### ISSUE TITLE
SKK(使用不可)

### ISSUE THREAD

**Issue by konomu** [fcitx/fcitx5-skk#15]
After building and installing, I added SKK to my input methods in fcitx5. But when I switch input method, the popup shows "SKK(使用不可)", and I can't type in Japanese.

Here is the output of fcitx5-diagnose:

# System Info:
1.  `uname -a`:

        Linux pasocon 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        Distributor ID:	Ubuntu
        Description:	Ubuntu 24.04 LTS
        Release:	24.04
        Codename:	noble

3.  `lsb_release -d`:

        Description:	Ubuntu 24.04 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=24.04
        DISTRIB_CODENAME=noble
        DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu 24.04 LTS"
        NAME="Ubuntu"
        VERSION_ID="24.04"
        VERSION="24.04 LTS (Noble Numbat)"
        VERSION_CODENAME=noble
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=noble
        LOGO=ubuntu-logo

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.21(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105+inet", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            ja_JP.utf8

    2.  Current locale:

            LANG=ja_JP.UTF-8
            LANGUAGE=ja:en_US:en
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/konomu

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/konomu/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/konomu/.config/fcitx5`).

5.  Current user:

    The script is run as konomu (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.7`

3.  process:

    Found 1 fcitx5 process:

          33779 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.176`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `33779`.

    Debug information from dbus:

           Group [x11::1] has 10 InputContext(s)
          IC [22879863bd1143e1b859ee9b5ec17a15] program: frontend:ibus cap:52 focus:0
          IC [3dcb1616169b4140a340557b38ed7848] program:org.gnome.Nautilus frontend:dbus cap:4000000072 focus:0
          IC [cfaf3db997bd44558e021ebfb782dd87] program:org.gnome.Nautilus frontend:dbus cap:4000021032 focus:0
          IC [0a25b1b84f8c45b2ae3952a2b416c1c6] program:sublime_text frontend:dbus cap:6000000020 focus:0
          IC [a2e5efa5fe3943e39e469621601cf9d1] program:firefox frontend:fcitx4 cap:12 focus:0
          IC [164228fff4dd497d9f7c6f8b5a5b4ff3] program:firefox frontend:fcitx4 cap:12 focus:0
          IC [43fd35e9dd4141879b156b742acac955] program:firefox frontend:fcitx4 cap:12 focus:0
          IC [18f2a17db0794c10982ee45510d15781] program:Discord frontend:dbus cap:6000000032 focus:0
          IC [8645afcd8ae94521adf0b14a8fb3ade0] program:gnome-terminal-server frontend:dbus cap:6000000032 focus:1
          IC [06d9b21e7d8f421795b80967ddb4bc38] program:firefox frontend:fcitx4 cap:52 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/lib/x86_64-linux-gnu/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/local/lib/fcitx5/qt6/libfcitx5-skk-config.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-gtk2-immodule-probing` not found.**

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0t64/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.41` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0t64/gtk-query-immodules-3.0 from gtk+-3.24.41

        Found fcitx5 im modules for gtk `3.24.41`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 22 enabled addons:

            Anthy 5.1.3
            Classic User Interface 5.1.7
            Clipboard 5.1.7
            DBus 5.1.7
            DBus Frontend 5.1.7
            Emoji 5.1.7
            Fcitx4 Frontend 5.1.7
            IBus Frontend 5.1.7
            Input method selector 5.1.7
            Keyboard 5.1.7
            KDE Input Method Panel 5.1.7
            Mozc 
            Status Notifier 5.1.7
            Notification 5.1.7
            Quick Phrase 5.1.7
            Spell 5.1.7
            Unicode 5.1.7
            DBus Virtual Keyboard 5.1.7
            Wayland 5.1.7
            Wayland Input method frontend 5.1.7
            XCB 5.1.7
            X Input Method Frontend 5.1.7

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/konomu/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=skk

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=skk
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Fri Jun 28 22:17:00 PDT 2024

2.  `/home/konomu/.config/fcitx5/crash.log`:

    `/home/konomu/.config/fcitx5/crash.log` not found.

**Comment by wengxt** [comment]
There is no standard to load library like xdg data dir etc, so you have to set FCITX_ADDON_DIRS to load addon under /usr/local or just set CMAKE_INSTALL_PREFIX to /usr .

**Comment by konomu** [comment]
Thank you, building with `cmake -DCMAKE_INSTALL_PREFIX=/usr .` solved my problem.
