### ISSUE TITLE
按了 l键 后就只能输入英文了

### ISSUE THREAD

**Issue by rsuu** [fcitx/fcitx5-skk#4]
此时再去点托盘图标的话  接无法切换到其他输入法

只有执行 fcitx5-configtool 或 重启fcitx5 才恢复正常

好吧  是我不会用

{
    "include": [
        "default"
    ],
    "define": {
        "keymap": {
            "q": "set-input-mode-hiragana",
            "Q": "start-preedit",
            "l": "set-input-mode-latin",
            "L": "set-input-mode-wide-latin",
            "C-q": "set-input-mode-hiragana",
	    "C-j": "commit"
        }
    }
}

**Comment by wengxt** [comment]
skk 是一种用法很特别的日语输入法（转换需要按住 Shift），比较符合一般人预期的推荐 kkc / mozc。

**Comment by rsuu** [comment]
fcitx5-mozc 是有什么额外配置吗   我一用图像界面就卡死了  只有鼠标能动  以及切换tty
Arch+i3
@wengxt
