### ISSUE TITLE
fcitx5-skk Dictionary Manager 's Button is not displayed correctly.

### ISSUE THREAD

**Issue by rkarsnk** [fcitx/fcitx5-skk#9]
fcitx5-skk Dictionary Manager 's Button is not displayed correctly.

Please tell me how to fix.

![2022_02_26_16_41_27](https://user-images.githubusercontent.com/26945036/155835008-6c81be34-f751-491a-a902-9ac9b95bba9c.png)

My envrionment:
- Debian 11(amd64)
- i3wm
- fcitx5 5.0.5-1/ fcitx5-skk 5.0.4-1 (from apt)

**Comment by wengxt** [comment]
it’s mostly a qt theme problem. There’s not much I can do here, you can try to use qt5ct and apply a theme.

I can try to make sure it can fall back to text label.

**Comment by rkarsnk** [comment]
>I can try to make sure it can fall back to text label.

I'd like to fall back to text label!

**Comment by rkarsnk** [comment]
@wengxt PR #10 screenshot.
- [OK] Button Label

![2022_02_28_15_40_31](https://user-images.githubusercontent.com/26945036/155936274-8f9d1612-8d9d-4145-9aa0-f108b10461ce.png)

- [OK] Japanese Translation

![2022_02_28_15_29_48](https://user-images.githubusercontent.com/26945036/155935973-a2fdc561-b43f-45e0-87f2-abe5198c951b.png)
